CREATE TABLE IF NOT EXISTS sky_signals_events (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    event_id VARCHAR(36) NOT NULL UNIQUE,
    type VARCHAR(32) NOT NULL,
    server VARCHAR(64) NOT NULL,
    scope VARCHAR(20) NOT NULL DEFAULT 'SERVER',
    scheduled_at TIMESTAMP NOT NULL,
    started_at TIMESTAMP NOT NULL,
    ended_at TIMESTAMP NULL,
    status VARCHAR(20) NOT NULL,
    phase VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    elapsed_seconds BIGINT DEFAULT 0,
    data JSON,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)